CREATE TABLE cliente(id_cliente number generated  by default as identity,
                                        nombre VARCHAR2(25),
                                        prioridad VARCHAR(6),
                                        telefono VARCHAR(12),
                                        NIF VARCHAR2(12),
                                        calle VARCHAR2(50),
                                        CP VARCHAR2(10),
                                        ciudad VARCHAR2(20),
                                        numero VARCHAR(3),
                                        PRIMARY KEY (id_cliente));
                                        
                                        
CREATE TABLE contacto(id_contacto number generated by default as identity,
                                            id_cliente number,
                                            nombre VARCHAR2(25),
                                            apellido1 VARCHAR2(20),
                                            apellido2 VARCHAR2(20),
                                            telefono VARCHAR2(12),
                                            cargo VARCHAR2(25),
                                            FOREIGN KEY (id_cliente) references cliente(id_cliente),
                                            PRIMARY KEY (id_contacto));


CREATE TABLE maquinas(id_maquinas number generated by default as identity,
                                            id_cliente number,
                                            tipo_maquina VARCHAR2(25),
                                            fecha_compra DATE,
                                            num_serie VARCHAR2(50),
                                            FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
                                            PRIMARY KEY (id_maquinas));
                                            
CREATE TABLE tecnico(id_tecnico number generated by default as identity,
                                        nombre VARCHAR2(25),
                                        apellido1 VARCHAR2(20),
                                        apellido2 VARCHAR2(20),
                                        DNI VARCHAR2(15),
                                        IBAN VARCHAR2(30),
                                        fecha_contratacion DATE,
                                        discapacidad char,
                                        PRIMARY KEY(id_tecnico));
drop table maquina;                                        
                                        
CREATE TABLE servicio(id_servicio number generated by default as identity,
                                        id_tecnico number,
                                        id_maquinas number,
                                        tarea_realizada VARCHAR2(60),
                                        maquina_reparada VARCHAR2(30),
                                        fecha_entrada timestamp,
                                        fecha_salida timestamp,
                                        pagado CHAR,
                                        FOREIGN KEY (id_maquinas) REFERENCES maquinas(id_maquinas),
                                        FOREIGN KEY (id_tecnico) REFERENCES tecnico(id_tecnico),
                                        PRIMARY KEY(id_servicio));
                                        
select * from servicio;

                                        
                                        
insert into cliente(nombre ,prioridad, telefono ,NIF,calle ,CP, ciudad, numero) values ('Innovación Digital S.A.', 'Alta', '+34912345678', 'A12345678', 'Avenida de la Tecnología', '28001', 'Madrid','15' );
insert into cliente(nombre ,prioridad, telefono ,NIF,calle ,CP, ciudad, numero) values ('TechSoluciones S.L.', 'Media', '+34987654321', 'B87654321', 'Calle de la Innovación', '46001', 'Valencia', '22');
insert into cliente(nombre ,prioridad, telefono ,NIF,calle ,CP, ciudad, numero) values ('EcoFuture Corp.', 'Baja', '+34911223344', 'C11223344', 'Paseo Verde', '41001', 'Sevilla', '10');

insert into contacto (id_cliente, nombre ,apellido1 ,apellido2 ,telefono,cargo) values ('2', 'Carlos', 'García', 'López', '+34987654321', 'Gerente de Operaciones');
insert into contacto (id_cliente, nombre ,apellido1 ,apellido2 ,telefono,cargo) values ('2', 'Laura', 'Martínez', 'Ruiz', '+34911223344', 'Responsable de IT');
insert into contacto (id_cliente, nombre ,apellido1 ,apellido2 ,telefono,cargo) values ('3', 'José', 'Fernández', 'Sánchez', '+34912345678', 'Jefe de Mantenimiento');


    insert into maquinas ( id_cliente ,tipo_maquina ,fecha_compra ,num_serie ) values ('4', 'Torno',to_date( '2022-05-10', 'yyyy/mm/dd'), 'TN12345X');
insert into maquinas ( id_cliente ,tipo_maquina ,fecha_compra ,num_serie ) values ('2', 'Fresa',to_date( '2021-08-15', 'yyyy/mm/dd'), 'FR67890Y');
insert into maquinas ( id_cliente ,tipo_maquina ,fecha_compra ,num_serie ) values ('2', 'Cortadora',to_date( '2023-03-20', 'yyyy/mm/dd'), 'CT11223Z');


insert into tecnico (nombre ,apellido1 ,apellido2 ,DNI ,IBAN ,fecha_contratacion ,discapacidad ) values ('Luis', 'Pérez', 'Gómez', '12345678A', 'ES7621000813610123456789',to_date ( '2020-02-15', 'yyyy/mm/dd'), 'N');
insert into tecnico (nombre ,apellido1 ,apellido2 ,DNI ,IBAN ,fecha_contratacion ,discapacidad ) values ('Marta', 'López', 'Hernández', '87654321B', 'ES9121000813610987654321',to_date ( '2019-07-10', 'yyyy/mm/dd'), 'S');
insert into tecnico (nombre ,apellido1 ,apellido2 ,DNI ,IBAN ,fecha_contratacion ,discapacidad ) values ('Javier', 'Ruiz', 'Martín', '45678912C', 'ES3021000813610456789123', to_date ('2021-11-05', 'yyyy/mm/dd'), 'N');


insert into servicio(id_tecnico , id_maquinas ,tarea_realizada, maquina_reparada, fecha_entrada, fecha_salida ,pagado) values ('2', '4', 'Cambio de rodamientos', 'Torno', to_timestamp('2023-06-14 08:30:00', 'yyyy/mm/dd hh24:mi:ss'), to_timestamp('2023-06-15 11:45','yyyy/mm/dd hh24:mi:ss'), 'S');
insert into servicio(id_tecnico , id_maquinas ,tarea_realizada, maquina_reparada, fecha_entrada, fecha_salida ,pagado) values ('4', '5', 'Ajuste de precisión', 'Fresa', to_timestamp('2023-07-19 09:00:00', 'yyyy/mm/dd hh24:mi:ss'), to_timestamp('2023-07-20 12:30', 'yyyy/mm/dd hh24:mi:ss'), 'N');
insert into servicio(id_tecnico , id_maquinas ,tarea_realizada, maquina_reparada, fecha_entrada, fecha_salida ,pagado) values ('2', '6', 'Reparación del motor', 'Cortadora', to_timestamp('2023-08-09 10:00:00', 'yyyy/mm/dd hh24:mi:ss'), to_timestamp('2023-08-10 14:15', 'yyyy/mm/dd hh24:mi:ss'), 'S');



 